/**
 * Shared bits for the Plan surface (/plan + /plan/generate): status-chip
 * metadata, date/duration formatting, badges, sub-score bars, and the
 * quality-warnings drill-in (plan.md §3a–§3c, §4c).
 */

import { SegmentBar } from "../../components/SegmentBar";
import { addDaysIso } from "../../mock/plannerSeed";
import type {
  PlanDto,
  PlanStatus,
  TriggerKind,
} from "../../mock/types";

/* ---- formatting ----------------------------------------------------------- */

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

/** "2026-06-08" → "8–14 June" (title week range, §3a). */
export function weekRangeLabel(weekStartDate: string): string {
  const end = addDaysIso(weekStartDate, 6);
  const sDay = Number(weekStartDate.slice(8));
  const eDay = Number(end.slice(8));
  const sMonth = MONTHS[Number(weekStartDate.slice(5, 7)) - 1];
  const eMonth = MONTHS[Number(end.slice(5, 7)) - 1];
  return sMonth === eMonth
    ? `${sDay}–${eDay} ${sMonth}`
    : `${sDay} ${sMonth} – ${eDay} ${eMonth}`;
}

/** "2026-06-11" → "Thu 11". */
export function shortDayLabel(iso: string): string {
  return new Date(`${iso}T12:00:00Z`).toLocaleDateString("en-GB", {
    weekday: "short",
    day: "numeric",
    timeZone: "UTC",
  });
}

/** ISO date-time → "Sun 7 June, 09:20". */
export function fmtDateTime(iso: string): string {
  const d = new Date(iso);
  return `${d.toLocaleDateString("en-GB", {
    weekday: "short",
    day: "numeric",
    month: "long",
    timeZone: "UTC",
  })}, ${iso.slice(11, 16)}`;
}

/** 220 → "3h 40m". */
export function fmtMinutes(min: number): string {
  const h = Math.floor(min / 60);
  const m = Math.round(min % 60);
  if (h === 0) return `${m}m`;
  return m === 0 ? `${h}h` : `${h}h ${m}m`;
}

/** "19:00" − 25 min → "18:35" (lead-time hint, §3d). */
export function leadTime(mealTime: string, budgetMin: number): string {
  const [h, m] = mealTime.split(":").map(Number);
  const t = Math.max(0, h * 60 + m - budgetMin);
  return `${String(Math.floor(t / 60)).padStart(2, "0")}:${String(t % 60).padStart(2, "0")}`;
}

/* ---- status + trigger labels ------------------------------------------------ */

export const STATUS_CHIP: Record<
  PlanStatus,
  { label: string; tone: "olive" | "amber" | "muted" }
> = {
  DRAFT: { label: "Draft", tone: "muted" }, // never rendered (§5)
  GENERATED: { label: "Awaiting approval", tone: "amber" },
  ACTIVE: { label: "Active", tone: "olive" },
  SUPERSEDED: { label: "Superseded", tone: "muted" },
  COMPLETED: { label: "Completed", tone: "muted" },
  REJECTED: { label: "Rejected", tone: "muted" },
  ABANDONED: { label: "Abandoned", tone: "muted" },
};

export function PlanStatusChip({ status }: { status: PlanStatus }) {
  const meta = STATUS_CHIP[status];
  return <span className={`mp-chip ${meta.tone}`}>{meta.label}</span>;
}

export const TRIGGER_LABEL: Record<TriggerKind, string> = {
  USER_INITIATED: "generated by you",
  SCHEDULED_WEEKLY: "auto-generated Sunday",
  MID_WEEK_REOPT: "mid-week re-optimisation",
};

/** Cold-start / AI-fallback badges (§3a). */
export function PlanBadges({ plan }: { plan: PlanDto }) {
  if (!plan.coldStart && plan.aiAugmented) return null;
  return (
    <div style={{ display: "flex", gap: 8, marginTop: 8, flexWrap: "wrap" }}>
      {plan.coldStart && (
        <span className="tint-chip terra">
          early-days plan — feedback especially valuable
        </span>
      )}
      {!plan.aiAugmented && (
        <span className="tint-chip muted-chip">
          AI ranking unavailable — top-scored pick
        </span>
      )}
    </div>
  );
}

/** Terminal/outcome metadata line for historical generations (§3a/§3f). */
export function planOutcomeLine(plan: PlanDto): string | null {
  if (plan.rejectedAt) {
    return `rejected ${fmtDateTime(plan.rejectedAt)}${
      plan.rejectedReason ? ` — “${plan.rejectedReason}”` : ""
    }`;
  }
  if (plan.abandonedAt) {
    return `abandoned ${fmtDateTime(plan.abandonedAt)}${
      plan.abandonedReason ? ` — “${plan.abandonedReason}”` : ""
    }`;
  }
  if (plan.completedAt) return `completed ${fmtDateTime(plan.completedAt)}`;
  if (plan.acceptedAt) return `accepted ${fmtDateTime(plan.acceptedAt)}`;
  return null;
}

/* ---- sub-score bars (§3c gate verdicts + §4c card) ----------------------------- */

const SCORE_KEYS = [
  ["preference", "Preference"],
  ["nutrition", "Nutrition"],
  ["cost", "Cost"],
  ["variety", "Variety"],
  ["time", "Time"],
  ["batch", "Batch"],
  ["provisions", "Provisions"],
] as const;

export function ScoreBars({ plan }: { plan: PlanDto }) {
  const sb = plan.scoreBreakdown;
  return (
    <div className="score-bars">
      {SCORE_KEYS.map(([key, label]) => (
        <div className="score-bar-row" key={key}>
          <span className="mp-label">{label}</span>
          <SegmentBar pct={sb[key]} segments={12} />
          <span className="mp-num" style={{ fontSize: 13 }}>
            {Math.round(sb[key] * 100)}%
          </span>
        </div>
      ))}
    </div>
  );
}

/* ---- quality warnings drill-in (§3c) -------------------------------------------- */

export function QualityWarningsPanel({ plan }: { plan: PlanDto }) {
  const weekly = plan.rollupSummary.weekly;
  const daily = plan.rollupSummary.daily;
  const sb = plan.scoreBreakdown;
  const unfilled = plan.days.flatMap((d) =>
    d.slots
      .filter((sl) => sl.scheduledRecipe === null && sl.kind !== "CUSTOM")
      .map((sl) => ({ date: d.date, label: sl.label })),
  );

  const gateRow = (passed: boolean, label: string) => (
    <div className="qw-row">
      <span
        style={{
          color: passed ? "var(--mp-olive)" : "var(--mp-amber)",
          fontWeight: 700,
        }}
      >
        {passed ? "✓" : "✗"}
      </span>
      <span>
        {label} — {passed ? "passed" : "failed"}
      </span>
    </div>
  );

  return (
    <div className="qw-panel mp-card" aria-label="Quality warnings detail">
      <span className="mp-label" style={{ color: "var(--mp-amber)" }}>
        Quality warnings · generation {plan.generation}
      </span>

      {weekly.constraintViolations.length > 0 && (
        <div className="qw-section">
          <span className="mp-label">Weekly violations</span>
          {weekly.constraintViolations.map((v) => (
            <div key={v} className="qw-row">
              <span style={{ color: "var(--mp-amber)" }}>⚠</span>
              <span>{v}</span>
            </div>
          ))}
        </div>
      )}

      {daily.some((d) => d.violations.length > 0) && (
        <div className="qw-section">
          <span className="mp-label">Per-day violations</span>
          {daily
            .filter((d) => d.violations.length > 0)
            .map((d) => (
              <div key={d.date} className="qw-row">
                <span className="qw-day">{shortDayLabel(d.date)}</span>
                <span>{d.violations.join(" · ")}</span>
              </div>
            ))}
        </div>
      )}

      {unfilled.length > 0 && (
        <div className="qw-section">
          <span className="mp-label">Unfilled slots</span>
          {unfilled.map((u) => (
            <div key={`${u.date}-${u.label}`} className="qw-row">
              <span className="qw-day">{shortDayLabel(u.date)}</span>
              <span>
                {u.label.toLowerCase()} — no feasible recipe found; relax a
                constraint or pick manually
              </span>
            </div>
          ))}
        </div>
      )}

      <div className="qw-section">
        <span className="mp-label">Gate verdicts</span>
        {gateRow(sb.nutritionFloorGatePassed, "Daily nutrition floors")}
        {gateRow(sb.varietyGatePassed, "Max-repeat variety rule")}
      </div>

      <div className="qw-section">
        <span className="mp-label">
          Sub-scores · composite {Math.round(sb.composite * 100)} / 100
        </span>
        <ScoreBars plan={plan} />
      </div>

      <div className="qw-section">
        <span className="mp-label">Per-day footer</span>
        <div className="qw-table-scroll">
          <table className="qw-table">
            <thead>
              <tr>
                <th />
                <th>kcal</th>
                <th>P g</th>
                <th>C g</th>
                <th>F g</th>
                <th>Fb g</th>
                <th>£</th>
                <th>time</th>
              </tr>
            </thead>
            <tbody>
              {daily.map((d) => (
                <tr key={d.date}>
                  <td>{shortDayLabel(d.date)}</td>
                  <td>{d.kcal.toLocaleString("en-GB")}</td>
                  <td>{d.proteinG}</td>
                  <td>{d.carbsG}</td>
                  <td>{d.fatG}</td>
                  <td>{d.fibreG}</td>
                  <td>{d.costGbp.toFixed(2)}</td>
                  <td>{fmtMinutes(d.totalTimeMin)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {unfilled.length > 0 && (
        <div className="inline-note">
          Unfilled rows are derived from scheduledRecipe = null — the contract
          cannot distinguish "planner failed to fill" from an intentionally
          empty slot (e.g. eating out). Flagged on the spec PR.
        </div>
      )}
    </div>
  );
}
