package com.example.mealprep.core.types;

/**
 * Trust tier carried by every recipe per {@code design/system-overview.md}. Influences how
 * downstream code handles ambiguity — low-trust recipes get a UI badge and stricter
 * nutrition-mapping flags.
 */
public enum DataQuality {
  /** Manually entered or confirmed by the user. Highest trust. */
  USER_VERIFIED,
  /** Extracted from a URL via the recipe-extraction pipeline. Medium trust. */
  IMPORTED,
  /** Generated by an AI task. Medium trust; internally consistent but unverified. */
  AI_GENERATED,
  /** Scraped from search results. Lowest trust. */
  WEB_DISCOVERED
}
