package com.example.mealprep.e2e.steps;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.mealprep.ai.spi.TaskType;
import com.example.mealprep.e2e.support.ApiClient;
import com.example.mealprep.e2e.support.ScenarioContext;
import com.example.mealprep.e2e.support.TestPayloads;
import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.restassured.response.Response;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Planner step definitions (planner.md): the week-scale plan orchestrator exercised over the
 * black-box HTTP API (decision D2). The planner is the hard half of Batch 2.
 *
 * <p><b>The load-bearing findings that shape this feature</b> (from reading {@code
 * PlansController}, {@code PlanComposer}, {@code PlanCompositionContextBuilder}, {@code
 * PlanPersister}, {@code NoOpRecipePoolSource}):
 *
 * <ul>
 *   <li><b>Generate's one hard precondition is a household.</b> {@code POST /api/v1/plans/generate}
 *       takes {@code householdId}; the controller 403s a non-member and the context builder fans
 *       out per household member. There IS a real public create path — {@code POST
 *       /api/v1/households} makes the caller the primary member AND seeds default slot settings
 *       (breakfast/lunch/dinner/ snack) — so the precondition is assemblable over HTTP with NO
 *       seeder. Preferences / nutrition / provisions are all read with {@code .ifPresent} / an
 *       empty-bundle fallback, so their absence does not block generation.
 *   <li><b>Generate is SYNCHRONOUS.</b> {@code compose} is {@code @Transactional} and the
 *       controller returns 201 + the persisted {@code PlanDto} inline (200 on an {@code
 *       Idempotency-Key} replay). No polling — the plan is GENERATED by the time the response
 *       returns.
 *   <li><b>Generate dispatches the AI — it must be primed.</b> The recipe-SEARCH pool warns empty
 *       ({@code NoOpRecipePoolSource}; no catalogue-wide search surface wired), but Stage A still
 *       yields candidate(s), so the composer runs Stage C ({@code PLANNER_STAGE_C}) and Phase 2
 *       ({@code PLANNER_PHASE2_AUGMENTATION}) inside the request. Both cross {@code AiService}, so
 *       the generate step primes the e2e AI stub with minimal safe responses (pick candidate 0; no
 *       augmentations) — without that the unprimed stub throws and the controller returns HTTP 502
 *       ({@code AiInvalidResponseException} -> {@code AiExceptionHandler}). The persisted plan is
 *       {@code GENERATED}.
 * </ul>
 *
 * <p><b>What is green vs @pending.</b> Green: generate (201 + GENERATED, AI primed), accept (->
 * ACTIVE), reject (-> REJECTED), abandon (-> ABANDONED), revert (-> 201 new GENERATED gen2 + prior
 * SUPERSEDED), the empty-state reads (active 404 / history empty / list empty / suggestions empty),
 * 404 on an unknown plan id, the cross-household 403, and the illegal-transition 409/400 errors.
 * Also green now that the planner plans from the recipe catalogue (Tier-1 {@code
 * CatalogueRecipePoolSource}): the slot-state lifecycle (PLAN-18) and the recipe-driven flagship
 * (PLAN-40) — both seed plannable recipes over the real {@code POST /api/v1/recipes} create path
 * (see {@link #theUserHasPlannableRecipesInTheirCatalogue()}) so Stage A produces candidates and a
 * generated plan carries real scheduled-recipe slots.
 *
 * <p>Self-contained (D5): every scenario mints its OWN fresh user, creates its OWN household, and
 * plans a per-scenario-random week, asserting only on THIS plan's id / status / generation
 * (self-scoped) — never a global plan count.
 */
public class PlannerSteps {

  private static final String PLANS = "/api/v1/plans";
  private static final String HOUSEHOLDS = "/api/v1/households";

  private static final String HOUSEHOLD_ID = "planner.householdId";
  private static final String WEEK_START = "planner.weekStart";
  private static final String PLAN_ID = "planner.planId";

  /**
   * The four built-in slot kinds {@code POST /api/v1/households} seeds by default
   * (breakfast/lunch/dinner/snack — see {@code HouseholdServiceImpl.buildDefaultSettings}). The
   * generated week has one slot per kind per day, so the seeded pool must cover every kind.
   */
  private static final List<String> DEFAULT_SLOT_KINDS =
      List.of("breakfast", "lunch", "dinner", "snack");

  /**
   * Recipes seeded per slot kind. 3 matches the planner's {@code min-pool-per-slot}; 3 × 4 kinds =
   * 12 total stays at/above the cold-start threshold ({@code 3 × 4 distinct kinds}), so the
   * cold-start gate does not fire and the plan fills from the seeded USER catalogue alone.
   */
  private static final int RECIPES_PER_KIND = 3;

  private final ScenarioContext context;
  private final AiStubSteps aiStub;

  public PlannerSteps(ScenarioContext context, AiStubSteps aiStub) {
    this.context = context;
    this.aiStub = aiStub;
  }

  // ---------------- preconditions (real HTTP create paths) ----------------

  @Given("the user has a household")
  public void theUserHasAHousehold() {
    // POST /api/v1/households makes the caller the primary member and seeds default slot settings —
    // the sole hard precondition for generate. Assert 201 so a wiring failure fails the setup
    // loudly
    // rather than surfacing as a confusing 403 in the generate step.
    Response response =
        context.api().post(HOUSEHOLDS, Map.of("name", "E2E Household " + shortId()));
    context.setLastResponse(response);
    assertThat(response.statusCode())
        .as("household create should return 201 Created")
        .isEqualTo(201);
    String householdId = response.jsonPath().getString("id");
    assertThat(householdId).as("create must mint a household id").isNotBlank();
    context.put(HOUSEHOLD_ID, householdId);
  }

  /**
   * Seed a plannable recipe pool over the real HTTP create path ({@code POST /api/v1/recipes}) so
   * Stage A produces candidates for every default-household slot kind. The default household
   * (created by {@link #theUserHasAHousehold()}) seeds all four built-in slot kinds —
   * breakfast/lunch/dinner/snack — so the generated week has 4 slots per day. Seed {@code
   * RECIPES_PER_KIND} (= 3) recipes per kind = 12 total, which clears both the planner's {@code
   * min-pool-per-slot} (3) AND the cold-start threshold ({@code 3 × distinct-slot-kinds} = 12), so
   * the cold-start gate does NOT fire — the plan is filled from THIS user's seeded USER catalogue
   * alone (deterministic, self-scoped). Each recipe carries an empty {@code equipmentRequired} and
   * a small {@code totalTimeMins} so it survives the Stage-A hard filters for a fresh household
   * with no provisions (see {@link TestPayloads#plannableRecipe}).
   */
  @Given("the user has plannable recipes in their catalogue")
  public void theUserHasPlannableRecipesInTheirCatalogue() {
    for (String mealType : DEFAULT_SLOT_KINDS) {
      for (int i = 0; i < RECIPES_PER_KIND; i++) {
        String name = "E2E " + mealType + " " + (i + 1) + " " + shortId();
        Response response =
            context.api().post("/api/v1/recipes", TestPayloads.plannableRecipe(name, mealType));
        assertThat(response.statusCode())
            .as("seeding a plannable %s recipe should return 201 Created", mealType)
            .isEqualTo(201);
      }
    }
  }

  // ---------------- generate + lifecycle ----------------

  @When("they generate a plan for a week")
  public void theyGenerateAPlanForAWeek() {
    // Synchronous: the composer runs Stage A->D inside the request and returns the persisted plan.
    // Stage A yields >=1 candidate (the recipe-SEARCH pool warns empty, but the candidate list is
    // not), so Stage C (PLANNER_STAGE_C) and Phase 2 (PLANNER_PHASE2_AUGMENTATION) BOTH dispatch
    // the
    // AI inside the request; an unprimed stub throws AiInvalidResponseException -> HTTP 502. Prime
    // minimal safe responses: pick candidate 0 (an out-of-range index falls back deterministically)
    // and apply no augmentations.
    aiStub.primeAi(
        TaskType.PLANNER_STAGE_C, "{\"chosenIndex\":0,\"reasoning\":\"e2e deterministic pick\"}");
    aiStub.primeAi(
        TaskType.PLANNER_PHASE2_AUGMENTATION, "{\"augmentations\":[],\"refineDirectives\":[]}");
    // A per-scenario-random Monday keeps the (household, week) self-contained.
    LocalDate weekStart = nextMonday();
    context.put(WEEK_START, weekStart.toString());
    Map<String, Object> body =
        Map.of(
            "householdId", context.<String>get(HOUSEHOLD_ID),
            "weekStartDate", weekStart.toString(),
            "forceRegenerateIfActive", false);
    context.setLastResponse(context.api().post(PLANS + "/generate", body));
  }

  @Then("a generated plan is created for this household")
  public void aGeneratedPlanIsCreatedForThisHousehold() {
    Response response = context.lastResponse();
    assertThat(response.statusCode()).as("generate should return 201 Created").isEqualTo(201);
    assertThat(response.jsonPath().getString("status")).isEqualTo("GENERATED");
    assertThat(response.jsonPath().getString("householdId"))
        .isEqualTo(context.<String>get(HOUSEHOLD_ID));
    assertThat(response.jsonPath().getInt("generation")).isEqualTo(1);
    rememberPlan(response);
  }

  @When("they accept that plan")
  public void theyAcceptThatPlan() {
    context.setLastResponse(context.api().post(PLANS + "/" + planId() + "/accept", Map.of()));
  }

  @Then("the plan becomes active for this household")
  public void thePlanBecomesActiveForThisHousehold() {
    Response response = context.lastResponse();
    assertThat(response.statusCode()).as("accept should return 200 OK").isEqualTo(200);
    assertThat(response.jsonPath().getString("status")).isEqualTo("ACTIVE");
    assertThat(response.jsonPath().getString("id")).isEqualTo(planId());
    assertThat(response.jsonPath().getString("acceptedAt")).isNotBlank();
  }

  @When("they reject that plan")
  public void theyRejectThatPlan() {
    context.setLastResponse(
        context.api().post(PLANS + "/" + planId() + "/reject", Map.of("reason", "not this week")));
  }

  @Then("the plan is rejected for this household")
  public void thePlanIsRejectedForThisHousehold() {
    Response response = context.lastResponse();
    assertThat(response.statusCode()).as("reject should return 200 OK").isEqualTo(200);
    assertThat(response.jsonPath().getString("status")).isEqualTo("REJECTED");
    assertThat(response.jsonPath().getString("id")).isEqualTo(planId());
  }

  @When("they abandon that plan")
  public void theyAbandonThatPlan() {
    context.setLastResponse(
        context.api().post(PLANS + "/" + planId() + "/abandon", Map.of("reason", "going away")));
  }

  @Then("the plan is abandoned for this household")
  public void thePlanIsAbandonedForThisHousehold() {
    Response response = context.lastResponse();
    assertThat(response.statusCode()).as("abandon should return 200 OK").isEqualTo(200);
    assertThat(response.jsonPath().getString("status")).isEqualTo("ABANDONED");
    assertThat(response.jsonPath().getString("id")).isEqualTo(planId());
  }

  @When("they revert that active plan")
  public void theyRevertThatActivePlan() {
    context.setLastResponse(context.api().post(PLANS + "/" + planId() + "/revert", Map.of()));
  }

  @Then("a fresh generation is created and the prior plan is superseded for this household")
  public void aFreshGenerationIsCreatedAndThePriorPlanIsSupersededForThisHousehold() {
    // Revert is copy-forward: a NEW plan (generation 2, GENERATED) is created (201) and the prior
    // active is superseded. Assert the new generation here; the prior is left as SUPERSEDED in the
    // DB
    // (its supersede is the documented side effect, asserted via the new plan's replacesPlanId).
    Response response = context.lastResponse();
    assertThat(response.statusCode()).as("revert should return 201 Created").isEqualTo(201);
    assertThat(response.jsonPath().getString("status")).isEqualTo("GENERATED");
    assertThat(response.jsonPath().getInt("generation")).isEqualTo(2);
    assertThat(response.jsonPath().getString("replacesPlanId")).isEqualTo(planId());
  }

  // ---------------- illegal transitions ----------------

  @Then("the accept is rejected as an illegal plan transition")
  public void theAcceptIsRejectedAsAnIllegalPlanTransition() {
    // Accepting a non-GENERATED plan (e.g. an already-ACTIVE one) is an illegal transition -> 409.
    assertThat(context.lastResponse().statusCode())
        .as("accepting a non-GENERATED plan must be 409 Conflict")
        .isEqualTo(409);
  }

  @When("they revert that generated plan")
  public void theyRevertThatGeneratedPlan() {
    context.setLastResponse(context.api().post(PLANS + "/" + planId() + "/revert", Map.of()));
  }

  @Then("the revert is rejected because the plan is not active")
  public void theRevertIsRejectedBecauseThePlanIsNotActive() {
    // Reverting a non-ACTIVE plan (a GENERATED one) is a bad request -> 400 (PlanNotReoptable).
    assertThat(context.lastResponse().statusCode())
        .as("reverting a non-ACTIVE plan must be 400 Bad Request")
        .isEqualTo(400);
  }

  // ---------------- reads (empty-state + not-found) ----------------

  @When("they read the active plan for a never-planned week")
  public void theyReadTheActivePlanForANeverPlannedWeek() {
    String week = nextMonday().toString();
    context.setLastResponse(
        context
            .api()
            .get(
                PLANS
                    + "/active?householdId="
                    + context.<String>get(HOUSEHOLD_ID)
                    + "&weekStartDate="
                    + week));
  }

  @Then("the active plan read is rejected as not found")
  public void theActivePlanReadIsRejectedAsNotFound() {
    assertThat(context.lastResponse().statusCode())
        .as("no active plan for a never-planned week must be 404 Not Found")
        .isEqualTo(404);
  }

  @When("they read the plan history for a never-planned week")
  public void theyReadThePlanHistoryForANeverPlannedWeek() {
    String week = nextMonday().toString();
    context.setLastResponse(
        context
            .api()
            .get(
                PLANS
                    + "/history?householdId="
                    + context.<String>get(HOUSEHOLD_ID)
                    + "&weekStartDate="
                    + week));
  }

  @Then("the plan history is empty for this household")
  public void thePlanHistoryIsEmptyForThisHousehold() {
    // getHistory returns a 200 + JSON array (not a Page); a never-planned week yields an empty
    // list.
    Response response = context.lastResponse();
    assertThat(response.statusCode()).as("plan history should return 200 OK").isEqualTo(200);
    assertThat(response.jsonPath().getList("$")).as("plan history list").isEmpty();
  }

  @When("they read pending re-opt suggestions for this household")
  public void theyReadPendingReoptSuggestionsForThisHousehold() {
    context.setLastResponse(
        context.api().get(PLANS + "/suggestions?householdId=" + context.<String>get(HOUSEHOLD_ID)));
  }

  @Then("the re-opt suggestion list is empty for this household")
  public void theReoptSuggestionListIsEmptyForThisHousehold() {
    Response response = context.lastResponse();
    assertThat(response.statusCode()).as("suggestions should return 200 OK").isEqualTo(200);
    assertThat(response.jsonPath().getList("content")).as("suggestions content").isEmpty();
    assertThat(response.jsonPath().getLong("totalElements"))
        .as("suggestions totalElements")
        .isZero();
  }

  @When("they read a plan by a random non-existent id")
  public void theyReadAPlanByARandomNonExistentId() {
    context.setLastResponse(context.api().get(PLANS + "/" + UUID.randomUUID()));
  }

  @Then("the plan read is rejected as not found")
  public void thePlanReadIsRejectedAsNotFound() {
    assertThat(context.lastResponse().statusCode())
        .as("a read of an unknown plan id must be 404 Not Found")
        .isEqualTo(404);
  }

  @When("an anonymous client generates a plan with no session")
  public void anAnonymousClientGeneratesAPlanWithNoSession() {
    // A FRESH client (its own empty cookie jar) is unambiguously anonymous; the deny-by-default
    // chain must 401 before any planner logic. A syntactically valid body is sent so the 401 is
    // attributable to the missing session, not body validation.
    Map<String, Object> body =
        Map.of(
            "householdId", UUID.randomUUID().toString(),
            "weekStartDate", nextMonday().toString(),
            "forceRegenerateIfActive", false);
    context.setLastResponse(new ApiClient().post(PLANS + "/generate", body));
  }

  // ---------------- recipe-pool-driven glue (green; the catalogue now feeds Stage A) ----------
  // These steps assert on scheduled-recipe slots. They are reached after seeding plannable recipes
  // over POST /api/v1/recipes (theUserHasPlannableRecipesInTheirCatalogue), so a generated plan has
  // real slots — the slot-state lifecycle (PLAN-18) and the AI flagship (PLAN-40) are now green.

  @When("they mark the first slot of that plan cooking")
  public void theyMarkTheFirstSlotOfThatPlanCooking() {
    // Read the plan and PATCH its first slot PLANNED -> COOKING. The seeded catalogue gave Stage A
    // candidates, so days[0].slots[0] (slotIndex 0 = breakfast) is a filled, transitionable slot.
    Response plan = context.api().get(PLANS + "/" + planId());
    String slotId = plan.jsonPath().getString("days[0].slots[0].id");
    context.setLastResponse(
        context
            .api()
            .request()
            .body(Map.of("newState", "COOKING"))
            .when()
            .patch(PLANS + "/" + planId() + "/slots/" + slotId + "/state"));
  }

  @Then("the slot is marked cooking for this household")
  public void theSlotIsMarkedCookingForThisHousehold() {
    Response response = context.lastResponse();
    assertThat(response.statusCode()).as("slot-state PATCH should return 200 OK").isEqualTo(200);
    assertThat(response.jsonPath().getString("days[0].slots[0].state")).isEqualTo("COOKING");
  }

  @And("the AI will pick the recommended plan candidate")
  public void theAiWillPickTheRecommendedPlanCandidate() {
    // The Stage-C pick task (TaskType PLANNER_STAGE_C, output {chosenIndex, reasoning}). Stage C
    // runs once the seeded catalogue gives Stage A candidates to choose from; pick candidate 0
    // deterministically (an out-of-range index falls back deterministically).
    aiStub.primeAi(
        com.example.mealprep.ai.spi.TaskType.PLANNER_STAGE_C,
        "{ \"chosenIndex\": 0, \"reasoning\": \"balanced macros and good variety\" }");
  }

  @Then("the generated plan has scheduled recipes in its slots for this household")
  public void theGeneratedPlanHasScheduledRecipesInItsSlotsForThisHousehold() {
    Response response = context.lastResponse();
    assertThat(response.statusCode()).as("generate should return 201 Created").isEqualTo(201);
    assertThat(response.jsonPath().getString("status")).isEqualTo("GENERATED");
    assertThat(response.jsonPath().getString("householdId"))
        .isEqualTo(context.<String>get(HOUSEHOLD_ID));
    assertThat(response.jsonPath().getList("days")).as("the plan should have days").isNotEmpty();
    assertThat(response.jsonPath().getString("days[0].slots[0].scheduledRecipe.recipeId"))
        .as("a slot should carry a scheduled recipe")
        .isNotBlank();
    rememberPlan(response);
  }

  @Then("the first plan is a cold-start plan with scheduled recipes for this household")
  public void theFirstPlanIsAColdStartPlanWithScheduledRecipesForThisHousehold() {
    // XJ-06: the empty catalogue tripped the Tier-2 cold-start gate, which ran discovery
    // (E2eSeedDiscoverySource in the e2e profile) to fill the SYSTEM catalogue; the re-read pool
    // then filled the plan's slots. Assert the gate fired (coldStart = true, exposed on PlanDto)
    // and
    // the plan carries scheduled recipes — the cold-start DoD over HTTP. The deterministic seed
    // covers breakfast/lunch/dinner, so the first day's first slot (slotIndex 0 = breakfast) is
    // filled; the snack slot has no seed and is simply omitted (unfilled slots are not persisted).
    Response response = context.lastResponse();
    assertThat(response.statusCode()).as("generate should return 201 Created").isEqualTo(201);
    assertThat(response.jsonPath().getString("status")).isEqualTo("GENERATED");
    assertThat(response.jsonPath().getString("householdId"))
        .isEqualTo(context.<String>get(HOUSEHOLD_ID));
    assertThat(response.jsonPath().getBoolean("coldStart"))
        .as("an empty-catalogue first plan should be flagged cold-start")
        .isTrue();
    assertThat(response.jsonPath().getList("days")).as("the plan should have days").isNotEmpty();
    assertThat(response.jsonPath().getString("days[0].slots[0].scheduledRecipe.recipeId"))
        .as("a cold-start-imported recipe should fill the first slot")
        .isNotBlank();
    rememberPlan(response);
  }

  // ---------------- helpers ----------------

  private void rememberPlan(Response response) {
    context.put(PLAN_ID, response.jsonPath().getString("id"));
  }

  private String planId() {
    return context.get(PLAN_ID);
  }

  /** A future Monday so each scenario's (household, week) is clean (no Monday rule, just tidy). */
  private static LocalDate nextMonday() {
    LocalDate d = LocalDate.now().plusDays(7);
    while (d.getDayOfWeek() != java.time.DayOfWeek.MONDAY) {
      d = d.plusDays(1);
    }
    return d;
  }

  private static String shortId() {
    return UUID.randomUUID().toString().substring(0, 8);
  }
}
