package com.example.mealprep.core.audit.api.dto;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.UUID;

/**
 * Write DTO for {@link com.example.mealprep.core.audit.domain.service.DecisionLogService#write}.
 *
 * <p>The {@code decisionId} is generated by the service — callers do not supply one. All other
 * fields are required unless explicitly nullable per the comments below.
 */
public record DecisionLogWriteRequest(
    UUID traceId,
    UUID parentDecisionId, // nullable — null for trace roots
    String scopeKind,
    UUID scopeId,
    DecisionLogScale scale,
    String triggeredBy,
    UUID actorUserId, // nullable — null for system-initiated
    JsonNode inputs,
    JsonNode candidates, // nullable
    JsonNode chosen, // nullable
    String reasoning, // nullable
    JsonNode emittedDirective, // nullable
    int iteration,
    Integer durationMs // nullable
    ) {}
